export const ActionTypes = {
    FETCH_SEARCH_ITEMS_START: 'FETCH_SEARCH_ITEMS_START',
    FETCH_SEARCH_ITEMS_SUCCESS: 'FETCH_SEARCH_ITEMS_SUCCESS',
    FETCH_SEARCH_ITEMS_FAIL: 'FETCH_SEARCH_ITEMS_FAIL',
    CLEAR_ERROR: 'CLEAR_ERROR'
}
