export const ActionTypes = {
    FETCH_USER_COMMENTS_START: 'FETCH_USER_COMMENTS_START',
    FETCH_USER_COMMENTS_SUCCESS: 'FETCH_USER_COMMENTS_SUCCESS',
    FETCH_USER_COMMENTS_FAIL: 'FETCH_USER_COMMENTS_FAIL',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    INIT_STATE: 'INIT_STATE'
}
