export const ActionTypes = {
    FETCH_USER_DATA_START: 'FETCH_USER_DATA_START',
    FETCH_USER_DATA_SUCCESS: 'FETCH_USER_DATA_SUCCESS',
    FETCH_USER_DATA_FAIL: 'FETCH_USER_DATA_FAIL',
    UPDATE_USER_DATA_START: 'UPDATE_USER_DATA_START',
    UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
    UPDATE_USER_DATA_FAIL: 'UPDATE_USER_DATA_FAIL'
}
