export const ActionTypes = {
    FETCH_USER_DATA_START: 'FETCH_USER_DATA_START',
    FETCH_USER_DATA_SUCCESS: 'FETCH_USER_DATA_SUCCESS',
    FETCH_USER_DATA_FAIL: 'FETCH_USER_DATA_FAIL',
    UPDATE_USER_DATA_START: 'UPDATE_USER_DATA_START',
    UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
    UPDATE_USER_DATA_FAIL: 'UPDATE_USER_DATA_FAIL',
    UPDATE_USER_PASSWORD_START: 'UPDATE_USER_PASSWORD_START',
    UPDATE_USER_PASSWORD_SUCCESS: 'UPDATE_USER_PASSWORD_SUCCESS',
    UPDATE_USER_PASSWORD_FAIL: 'UPDATE_USER_PASSWORD_FAIL',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE'
}
