export const ActionTypes = {
    FETCH_USER_ORDERS_START: 'FETCH_USER_ORDERS_START',
    FETCH_USER_ORDERS_SUCCESS: 'FETCH_USER_ORDERS_SUCCESS',
    FETCH_USER_ORDERS_FAIL: 'FETCH_USER_ORDERS_FAIL',
    SAVE_USER_ORDER_START: 'SAVE_USER_ORDER_START',
    SAVE_USER_ORDER_SUCCESS: 'SAVE_USER_ORDER_SUCCESS',
    SAVE_USER_ORDER_FAIL: 'SAVE_USER_ORDER_FAIL',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    INIT_STATE: 'INIT_STATE'
}
