export const CartActionTypes = {
    ADD_ITEM_TO_THE_CART: 'ADD_ITEM_TO_THE_CART',
    DECREASE_ITEM: 'DECREASE_ITEM',
    REMOVE_ONE_ITEM_FROM_THE_CART: 'REMOVE_ONE_ITEM_FROM_THE_CART',
    REMOVE_ALL_ITEMS_FROM_THE_CART: 'REMOVE_ALL_ITEMS_FROM_THE_CART',
}