export const ActionTypes = {
    FETCH_USER_RATINGS_START: 'FETCH_USER_RATINGS_START',
    FETCH_USER_RATINGS_SUCCESS: 'FETCH_USER_RATINGS_SUCCESS',
    FETCH_USER_RATINGS_FAIL: 'FETCH_USER_RATINGS_FAIL',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    INIT_STATE: 'INIT_STATE'
}
