export const ActionTypes = {
    FETCH_USER_FAVORITES_START: 'FETCH_USER_FAVORITES_START',
    FETCH_USER_FAVORITES_SUCCESS: 'FETCH_USER_FAVORITES_SUCCESS',
    FETCH_USER_FAVORITES_FAIL: 'FETCH_USER_FAVORITES_FAIL',
    ADD_TO_USER_FAVORITES_START: 'ADD_TO_USER_FAVORITES_START',
    ADD_TO_USER_FAVORITES_SUCCESS: 'ADD_TO_USER_FAVORITES_SUCCESS',
    ADD_TO_USER_FAVORITES_FAIL: 'ADD_TO_USER_FAVORITES_FAIL',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    INIT_STATE: 'INIT_STATE'
}
